### ISSUE TITLE
integration fails after upgrade to home-assistant-core 2021.12.10

### ISSUE THREAD

**Issue by tafypz** [natekspencer/hacs-vivint#36] opened 2022-01-20 15:07 UTC
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 313, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/vivint/__init__.py", line 59, in async_setup_entry
    await hub.login(load_devices=True, subscribe_for_realtime_updates=True)
  File "/config/custom_components/vivint/hub.py", line 94, in login
    await self.account.connect(
  File "/usr/local/lib/python3.9/site-packages/vivintpy/account.py", line 72, in connect
    await self.subscribe_for_realtime_updates(authuser_data)
  File "/usr/local/lib/python3.9/site-packages/vivintpy/account.py", line 167, in subscribe_for_realtime_updates
    self.__pubnub = PubNubAsyncio(pnconfig)
  File "/usr/local/lib/python3.9/site-packages/pubnub/pubnub_asyncio.py", line 38, in __init__
    super(PubNubAsyncio, self).__init__(config)
  File "/usr/local/lib/python3.9/site-packages/pubnub/pubnub_core.py", line 78, in __init__
    self.config.validate()
  File "/usr/local/lib/python3.9/site-packages/pubnub/pnconfiguration.py", line 38, in validate
    def validate(self):
  File "/usr/local/lib/python3.9/site-packages/pubnub/pnconfiguration.py", line 41, in validate_not_empty_string
    if not self.uuid:
AssertionError: UUID missing or invalid type

**Comment by tschmorleiz** [comment] 2022-01-20 15:46
I'm having the same issue since the update to 2021.12.10.

**Comment by tschmorleiz** [comment] 2022-01-20 15:55
@tafypz Was fixed for me after updating the Vivint integration through HACS.

**Comment by natekspencer** [comment] 2022-01-20 16:25
Duplicate of #35. Fixed in latest release

**Closed by natekspencer** 2022-01-20 16:25 UTC

**Comment by tafypz** [comment] 2022-01-20 16:58
> 



> @tafypz Was fixed for me after updating the Vivint integration through HACS.

I updated to the latest vivint prior to updating to 2021.12.10, this caused the problem

**Comment by natekspencer** [comment] 2022-01-21 02:33
@tafypz you may need to reinstall this integration and restart HA again then as this issue is caused by this:

https://github.com/pubnub/python/releases/tag/v6.0.0

Which was corrected in this:

https://github.com/natekspencer/vivintpy/releases/tag/2022.1.0

Which was then corrected in this:

https://github.com/natekspencer/hacs-vivint/releases/tag/2022.1.0
