### ISSUE TITLE
Vivint not working after home assistant update 

### ISSUE THREAD

**Issue by oricalworks** [natekspencer/hacs-vivint#86] opened 2023-03-02 15:04 UTC
Home assistant not loading Vivint after latest update.

`2023-03-02 10:00:21.207 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration vivint which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-03-02 10:00:27.815 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry REDACTED for vivint
File "/config/custom_components/vivint/__init__.py", line 53, in async_setup_entry
File "/config/custom_components/vivint/hub.py", line 95, in login
File "/usr/local/lib/python3.10/site-packages/vivintpy/account.py", line 65, in connect
authuser_data = await self.vivintskyapi.connect()
File "/usr/local/lib/python3.10/site-packages/vivintpy/vivintskyapi.py", line 61, in connect
File "/usr/local/lib/python3.10/site-packages/vivintpy/vivintskyapi.py", line 56, in is_session_valid
cookies = self.__client_session.cookie_jar.filter_cookies(VIVINT_API_ENDPOINT)
2023-03-02 10:01:23.915 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry REDACTED for vivint
File "/config/custom_components/vivint/__init__.py", line 53, in async_setup_entry
File "/config/custom_components/vivint/hub.py", line 95, in login
File "/usr/local/lib/python3.10/site-packages/vivintpy/account.py", line 65, in connect
authuser_data = await self.vivintskyapi.connect()
File "/usr/local/lib/python3.10/site-packages/vivintpy/vivintskyapi.py", line 61, in connect
File "/usr/local/lib/python3.10/site-packages/vivintpy/vivintskyapi.py", line 56, in is_session_valid
cookies = self.__client_session.cookie_jar.filter_cookies(VIVINT_API_ENDPOINT)
2023-03-02 10:01:33.140 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry REDACTED for vivint
File "/config/custom_components/vivint/__init__.py", line 53, in async_setup_entry
File "/config/custom_components/vivint/hub.py", line 95, in login
File "/usr/local/lib/python3.10/site-packages/vivintpy/account.py", line 65, in connect
authuser_data = await self.vivintskyapi.connect()
File "/usr/local/lib/python3.10/site-packages/vivintpy/vivintskyapi.py", line 61, in connect
File "/usr/local/lib/python3.10/site-packages/vivintpy/vivintskyapi.py", line 56, in is_session_valid
cookies = self.__client_session.cookie_jar.filter_cookies(VIVINT_API_ENDPOINT) `

**Comment by natekspencer** [comment] 2023-03-03 15:18
Duplicate of #84

**Closed by natekspencer** 2023-03-03 15:18 UTC
