### ISSUE TITLE
Error setting up entry Vivint

### ISSUE THREAD

**Issue by Bobbyiv** [natekspencer/hacs-vivint#82] opened 2023-02-24 22:00 UTC
I have issue loading integration after updating Home Assistant to 2023.3.0b0 and still doesn't load in 2023.3.0b1. Was running Vivint 2023.2.1, updated to 2023.2.2 and still has issue loading.  This may be the same issue as #79.

Logger: homeassistant.config_entries
Source: custom_components/vivint/hub.py:94
Integration: Vivint ([documentation](https://github.com/natekspencer/hacs-vivint), [issues](https://github.com/natekspencer/hacs-vivint/issues))
First occurred: 7:55:52 AM (3 occurrences)
Last logged: 1:48:23 PM

Error setting up entry Vivint for vivint
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/vivint/__init__.py", line 53, in async_setup_entry
    await hub.login(load_devices=True, subscribe_for_realtime_updates=True)
  File "/config/custom_components/vivint/hub.py", line 94, in login
    await self.account.connect(
  File "/usr/local/lib/python3.10/site-packages/vivintpy/account.py", line 65, in connect
    authuser_data = await self.vivintskyapi.connect()
  File "/usr/local/lib/python3.10/site-packages/vivintpy/vivintskyapi.py", line 61, in connect
    if self.__has_custom_client_session and self.is_session_valid():
  File "/usr/local/lib/python3.10/site-packages/vivintpy/vivintskyapi.py", line 56, in is_session_valid
    cookies = self.__client_session.cookie_jar.filter_cookies(VIVINT_API_ENDPOINT)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/cookiejar.py", line 239, in filter_cookies
    self._do_expiration()
  File "/usr/local/lib/python3.10/site-packages/aiohttp/cookiejar.py", line 150, in _do_expiration
    self.clear(lambda x: False)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/cookiejar.py", line 115, in clear
    for (domain, path), cookie in self._cookies.items():
ValueError: too many values to unpack (expected 2)

**Comment by natekspencer** [comment] 2023-02-24 22:07
Duplicate of https://github.com/natekspencer/hacs-vivint/issues/79

**Closed by natekspencer** 2023-02-24 22:07 UTC

**Comment by Bobbyiv** [comment] 2023-02-24 22:11
Thank you.
