### ISSUE TITLE
Failed to setup message on startup of Home Assistant

### ISSUE THREAD

**Issue by bavera** [natekspencer/hacs-vivint#102] opened 2023-04-04 20:24 UTC
This started after upgrade to HA 2023.3.6 and Supervisor 2023.03.3.  Here are the error logs:

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/vivint/hub.py:94
Integration: Vivint (documentation, issues)
First occurred: 4:20:11 PM (1 occurrences)
Last logged: 4:20:11 PM

Error setting up entry brent.avera@gmail.com for vivint
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/vivint/__init__.py", line 59, in async_setup_entry
    await hub.login(load_devices=True, subscribe_for_realtime_updates=True)
  File "/config/custom_components/vivint/hub.py", line 94, in login
    await self.account.connect(
  File "/usr/local/lib/python3.10/site-packages/vivintpy/account.py", line 66, in connect
    authuser_data = await self.vivintskyapi.connect()
  File "/usr/local/lib/python3.10/site-packages/vivintpy/vivintskyapi.py", line 67, in connect
    authuser_data = await self.get_authuser_data()
  File "/usr/local/lib/python3.10/site-packages/vivintpy/vivintskyapi.py", line 97, in get_authuser_data
    resp = await self.__get("authuser")
  File "/usr/local/lib/python3.10/site-packages/vivintpy/vivintskyapi.py", line 382, in __get
    return await self.__call(
  File "/usr/local/lib/python3.10/site-packages/vivintpy/vivintskyapi.py", line 430, in __call
    resp = await method(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 493, in _request
    all_cookies = self._cookie_jar.filter_cookies(url)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/cookiejar.py", line 239, in filter_cookies
    self._do_expiration()
  File "/usr/local/lib/python3.10/site-packages/aiohttp/cookiejar.py", line 150, in _do_expiration
    self.clear(lambda x: False)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/cookiejar.py", line 115, in clear
    for (domain, path), cookie in self._cookies.items():
ValueError: too many values to unpack (expected 2)

**Comment by natekspencer** [comment] 2023-04-04 22:56
Duplicate of https://github.com/natekspencer/hacs-vivint/issues/84.

You'll need to upgrade to the latest version of this integration.

**Closed by natekspencer** 2023-04-04 22:56 UTC
